# (1) Apriori

Gunakan dataset ini : https://drive.google.com/file/d/1BqC-2d1ZYqFIFwdjdsW5bAAqNFh2AO4C/view?usp=share_link

Dan buatlah daftar support dan confidence untuk 2 item set dengan menggunakan dataset tersebut (hint : buatlah tabel tabulasi terlebih dahulu untuk memudahkan)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Data_Tab.xlsx',sheet_name='Sheet1')
df

,whole milk,pastry,salty snack,sausage,semi-finished bread,yogurt,soda,pickled vegetables,canned beer,misc. beverages,...,tropical fruit,sugar,butter milk,specialty chocolate,frozen meals,dental care,root vegetables,detergen,dish cleaner,cling film/bags
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
17,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [ ]:
df.sum()
df.columns
# 2 Item set
from itertools import permutations #Library untuk buat kombinasi barang

# Extract unique items.
rules = list(permutations(df.columns, 2))
rules

[('whole milk', 'pastry'),
 ('whole milk', 'salty snack'),
 ('whole milk', 'sausage'),
 ('whole milk', 'semi-finished bread'),
 ('whole milk', 'yogurt'),
 ('whole milk', 'soda'),
 ('whole milk', 'pickled vegetables'),
 ('whole milk', 'canned beer'),
 ('whole milk', 'misc. beverages'),
 ('whole milk', 'hygiene articles'),
 ('whole milk', 'rolls/buns'),
 ('whole milk', 'frankfurter'),
 ('whole milk', 'whipped/sour cream'),
 ('whole milk', 'curd'),
 ('whole milk', 'beef'),
 ('whole milk', 'white bread'),
 ('whole milk', 'butter'),
 ('whole milk', 'frozen vegetables'),
 ('whole milk', 'other vegetables'),
 ('whole milk', 'tropical fruit'),
 ('whole milk', 'sugar'),
 ('whole milk', 'butter milk'),
 ('whole milk', 'specialty chocolate'),
 ('whole milk', 'frozen meals'),
 ('whole milk', 'dental care'),
 ('whole milk', 'root vegetables'),
 ('whole milk', 'detergen'),
 ('whole milk', 'dish cleaner'),
 ('whole milk', 'cling film/bags'),
 ('pastry', 'whole milk'),
 ('pastry', 'salty snack'),
 ('pastry', 'sausage'),
 ('pastry', 'semi-finished bread'),
 ('pastry', 'yogurt'),
 ('pastry', 'soda'),
 ('pastry', 'pickled vegetables'),
 ('pastry', 'canned beer'),
 ('pastry', 'misc. beverages'),
 ('pastry', 'hygiene articles'),
 ('pastry', 'rolls/buns'),
 ('pastry', 'frankfurter'),
 ('pastry', 'whipped/sour cream'),
 ('pastry', 'curd'),
 ('pastry', 'beef'),
 ('pastry', 'white bread'),
 ('pastry', 'butter'),
 ('pastry', 'frozen vegetables'),
 ('pastry', 'other vegetables'),
 ('pastry', 'tropical fruit'),
 ('pastry', 'sugar'),
 ('pastry', 'butter milk'),
 ('pastry', 'specialty chocolate'),
 ('pastry', 'frozen meals'),
 ('pastry', 'dental care'),
 ('pastry', 'root vegetables'),
 ('pastry', 'detergen'),
 ('pastry', 'dish cleaner'),
 ('pastry', 'cling film/bags'),
 ('salty snack', 'whole milk'),
 ('salty snack', 'pastry'),
 ('salty snack', 'sausage'),
 ('salty snack', 'semi-finished bread'),
 ('salty snack', 'yogurt'),
 ('salty snack', 'soda'),
 ('salty snack', 'pickled vegetables'),
 ('salty snack', 'canned beer'),
 ('salty snack', 'misc. beverages'),
 ('salty snack', 'hygiene articles'),
 ('salty snack', 'rolls/buns'),
 ('salty snack', 'frankfurter'),
 ('salty snack', 'whipped/sour cream'),
 ('salty snack', 'curd'),
 ('salty snack', 'beef'),
 ('salty snack', 'white bread'),
 ('salty snack', 'butter'),
 ('salty snack', 'frozen vegetables'),
 ('salty snack', 'other vegetables'),
 ('salty snack', 'tropical fruit'),
 ('salty snack', 'sugar'),
 ('salty snack', 'butter milk'),
 ('salty snack', 'specialty chocolate'),
 ('salty snack', 'frozen meals'),
 ('salty snack', 'dental care'),
 ('salty snack', 'root vegetables'),
 ('salty snack', 'detergen'),
 ('salty snack', 'dish cleaner'),
 ('salty snack', 'cling film/bags'),
 ('sausage', 'whole milk'),
 ('sausage', 'pastry'),
 ('sausage', 'salty snack'),
 ('sausage', 'semi-finished bread'),
 ('sausage', 'yogurt'),
 ('sausage', 'soda'),
 ('sausage', 'pickled vegetables'),
 ('sausage', 'canned beer'),
 ('sausage', 'misc. beverages'),
 ('sausage', 'hygiene articles'),
 ('sausage', 'rolls/buns'),
 ('sausage', 'frankfurter'),
 ('sausage', 'whipped/sour cream'),
 ('sausage', 'curd'),
 ('sausage', 'beef'),
 ('sausage', 'white bread'),
 ('sausage', 'butter'),
 ('sausage', 'frozen vegetables'),
 ('sausage', 'other vegetables'),
 ('sausage', 'tropical fruit'),
 ('sausage', 'sugar'),
 ('sausage', 'butter milk'),
 ('sausage', 'specialty chocolate'),
 ('sausage', 'frozen meals'),
 ('sausage', 'dental care'),
 ('sausage', 'root vegetables'),
 ('sausage', 'detergen'),
 ('sausage', 'dish cleaner'),
 ('sausage', 'cling film/bags'),
 ('semi-finished bread', 'whole milk'),
 ('semi-finished bread', 'pastry'),
 ('semi-finished bread', 'salty snack'),
 ('semi-finished bread', 'sausage'),
 ('semi-finished bread', 'yogurt'),
 ('semi-finished bread', 'soda'),
 ('semi-finished bread', 'pickled vegetables'),
 ('semi-finished bread', 'canned beer'),
 ('semi-finished bread', 'misc. beverages'),
 ('semi-finished bread', 'hygiene articles'),
 ('semi-finished bread', 'rolls/buns'),
 ('semi-finished bread', 'frankfurter'),
 ('semi-finished bread', 'whipped/sour cream'),
 ('semi-finished bread', 'curd'),
 ('semi-finished bread', 'beef'),
 ('semi-finished bread', 'white bread'),
 ('semi-finished bread', 'butter'),
 ('semi-finished bread', 'frozen vegetables'),
 ('semi-finished bread', 'other vegetables'),
 ('semi-finished bread', 'tropical fruit'),
 ('semi-finished bread', 'sugar'),
 ('semi-finished bread', 'butter milk'),
 ('semi-finished bread', 'specialty chocolate'),
 ('semi-finished bread', 'frozen meals'),
 ('semi-finished bread', 'dental care'),
 ('semi-finished bread', 'root vegetables'),
 ('semi-finished bread', 'detergen'),
 ('semi-finished bread', 'dish cleaner'),
 ('semi-finished bread', 'cling film/bags'),
 ('yogurt', 'whole milk'),
 ('yogurt', 'pastry'),
 ('yogurt', 'salty snack'),
 ('yogurt', 'sausage'),
 ('yogurt', 'semi-finished bread'),
 ('yogurt', 'soda'),
 ('yogurt', 'pickled vegetables'),
 ('yogurt', 'canned beer'),
 ('yogurt', 'misc. beverages'),
 ('yogurt', 'hygiene articles'),
 ('yogurt', 'rolls/buns'),
 ('yogurt', 'frankfurter'),
 ('yogurt', 'whipped/sour cream'),
 ('yogurt', 'curd'),
 ('yogurt', 'beef'),
 ('yogurt', 'white bread'),
 ('yogurt', 'butter'),
 ('yogurt', 'frozen vegetables'),
 ('yogurt', 'other vegetables'),
 ('yogurt', 'tropical fruit'),
 ('yogurt', 'sugar'),
 ('yogurt', 'butter milk'),
 ('yogurt', 'specialty chocolate'),
 ('yogurt', 'frozen meals'),
 ('yogurt', 'dental care'),
 ('yogurt', 'root vegetables'),
 ('yogurt', 'detergen'),
 ('yogurt', 'dish cleaner'),
 ('yogurt', 'cling film/bags'),
 ('soda', 'whole milk'),
 ('soda', 'pastry'),
 ('soda', 'salty snack'),
 ('soda', 'sausage'),
 ('soda', 'semi-finished bread'),
 ('soda', 'yogurt'),
 ('soda', 'pickled vegetables'),
 ('soda', 'canned beer'),
 ('soda', 'misc. beverages'),
 ('soda', 'hygiene articles'),
 ('soda', 'rolls/buns'),
 ('soda', 'frankfurter'),
 ('soda', 'whipped/sour cream'),
 ('soda', 'curd'),
 ('soda', 'beef'),
 ('soda', 'white bread'),
 ('soda', 'butter'),
 ('soda', 'frozen vegetables'),
 ('soda', 'other vegetables'),
 ('soda', 'tropical fruit'),
 ('soda', 'sugar'),
 ('soda', 'butter milk'),
 ('soda', 'specialty chocolate'),
 ('soda', 'frozen meals'),
 ('soda', 'dental care'),
 ('soda', 'root vegetables'),
 ('soda', 'detergen'),
 ('soda', 'dish cleaner'),
 ('soda', 'cling film/bags'),
 ('pickled vegetables', 'whole milk'),
 ('pickled vegetables', 'pastry'),
 ('pickled vegetables', 'salty snack'),
 ('pickled vegetables', 'sausage'),
 ('pickled vegetables', 'semi-finished bread'),
 ('pickled vegetables', 'yogurt'),
 ('pickled vegetables', 'soda'),
 ('pickled vegetables', 'canned beer'),
 ('pickled vegetables', 'misc. beverages'),
 ('pickled vegetables', 'hygiene articles'),
 ('pickled vegetables', 'rolls/buns'),
 ('pickled vegetables', 'frankfurter'),
 ('pickled vegetables', 'whipped/sour cream'),
 ('pickled vegetables', 'curd'),
 ('pickled vegetables', 'beef'),
 ('pickled vegetables', 'white bread'),
 ('pickled vegetables', 'butter'),
 ('pickled vegetables', 'frozen vegetables'),
 ('pickled vegetables', 'other vegetables'),
 ('pickled vegetables', 'tropical fruit'),
 ('pickled vegetables', 'sugar'),
 ('pickled vegetables', 'butter milk'),
 ('pickled vegetables', 'specialty chocolate'),
 ('pickled vegetables', 'frozen meals'),
 ('pickled vegetables', 'dental care'),
 ('pickled vegetables', 'root vegetables'),
 ('pickled vegetables', 'detergen'),
 ('pickled vegetables', 'dish cleaner'),
 ('pickled vegetables', 'cling film/bags'),
 ('canned beer', 'whole milk'),
 ('canned beer', 'pastry'),
 ('canned beer', 'salty snack'),
 ('canned beer', 'sausage'),
 ('canned beer', 'semi-finished bread'),
 ('canned beer', 'yogurt'),
 ('canned beer', 'soda'),
 ('canned beer', 'pickled vegetables'),
 ('canned beer', 'misc. beverages'),
 ('canned beer', 'hygiene articles'),
 ('canned beer', 'rolls/buns'),
 ('canned beer', 'frankfurter'),
 ('canned beer', 'whipped/sour cream'),
 ('canned beer', 'curd'),
 ('canned beer', 'beef'),
 ('canned beer', 'white bread'),
 ('canned beer', 'butter'),
 ('canned beer', 'frozen vegetables'),
 ('canned beer', 'other vegetables'),
 ('canned beer', 'tropical fruit'),
 ('canned beer', 'sugar'),
 ('canned beer', 'butter milk'),
 ('canned beer', 'specialty chocolate'),
 ('canned beer', 'frozen meals'),
 ('canned beer', 'dental care'),
 ('canned beer', 'root vegetables'),
 ('canned beer', 'detergen'),
 ('canned beer', 'dish cleaner'),
 ('canned beer', 'cling film/bags'),
 ('misc. beverages', 'whole milk'),
 ('misc. beverages', 'pastry'),
 ('misc. beverages', 'salty snack'),
 ('misc. beverages', 'sausage'),
 ('misc. beverages', 'semi-finished bread'),
 ('misc. beverages', 'yogurt'),
 ('misc. beverages', 'soda'),
 ('misc. beverages', 'pickled vegetables'),
 ('misc. beverages', 'canned beer'),
 ('misc. beverages', 'hygiene articles'),
 ('misc. beverages', 'rolls/buns'),
 ('misc. beverages', 'frankfurter'),
 ('misc. beverages', 'whipped/sour cream'),
 ('misc. beverages', 'curd'),
 ('misc. beverages', 'beef'),
 ('misc. beverages', 'white bread'),
 ('misc. beverages', 'butter'),
 ('misc. beverages', 'frozen vegetables'),
 ('misc. beverages', 'other vegetables'),
 ('misc. beverages', 'tropical fruit'),
 ('misc. beverages', 'sugar'),
 ('misc. beverages', 'butter milk'),
 ('misc. beverages', 'specialty chocolate'),
 ('misc. beverages', 'frozen meals'),
 ('misc. beverages', 'dental care'),
 ('misc. beverages', 'root vegetables'),
 ('misc. beverages', 'detergen'),
 ('misc. beverages', 'dish cleaner'),
 ('misc. beverages', 'cling film/bags'),
 ('hygiene articles', 'whole milk'),
 ('hygiene articles', 'pastry'),
 ('hygiene articles', 'salty snack'),
 ('hygiene articles', 'sausage'),
 ('hygiene articles', 'semi-finished bread'),
 ('hygiene articles', 'yogurt'),
 ('hygiene articles', 'soda'),
 ('hygiene articles', 'pickled vegetables'),
 ('hygiene articles', 'canned beer'),
 ('hygiene articles', 'misc. beverages'),
 ('hygiene articles', 'rolls/buns'),
 ('hygiene articles', 'frankfurter'),
 ('hygiene articles', 'whipped/sour cream'),
 ('hygiene articles', 'curd'),
 ('hygiene articles', 'beef'),
 ('hygiene articles', 'white bread'),
 ('hygiene articles', 'butter'),
 ('hygiene articles', 'frozen vegetables'),
 ('hygiene articles', 'other vegetables'),
 ('hygiene articles', 'tropical fruit'),
 ('hygiene articles', 'sugar'),
 ('hygiene articles', 'butter milk'),
 ('hygiene articles', 'specialty chocolate'),
 ('hygiene articles', 'frozen meals'),
 ('hygiene articles', 'dental care'),
 ('hygiene articles', 'root vegetables'),
 ('hygiene articles', 'detergen'),
 ('hygiene articles', 'dish cleaner'),
 ('hygiene articles', 'cling film/bags'),
 ('rolls/buns', 'whole milk'),
 ('rolls/buns', 'pastry'),
 ('rolls/buns', 'salty snack'),
 ('rolls/buns', 'sausage'),
 ('rolls/buns', 'semi-finished bread'),
 ('rolls/buns', 'yogurt'),
 ('rolls/buns', 'soda'),
 ('rolls/buns', 'pickled vegetables'),
 ('rolls/buns', 'canned beer'),
 ('rolls/buns', 'misc. beverages'),
 ('rolls/buns', 'hygiene articles'),
 ('rolls/buns', 'frankfurter'),
 ('rolls/buns', 'whipped/sour cream'),
 ('rolls/buns', 'curd'),
 ('rolls/buns', 'beef'),
 ('rolls/buns', 'white bread'),
 ('rolls/buns', 'butter'),
 ('rolls/buns', 'frozen vegetables'),
 ('rolls/buns', 'other vegetables'),
 ('rolls/buns', 'tropical fruit'),
 ('rolls/buns', 'sugar'),
 ('rolls/buns', 'butter milk'),
 ('rolls/buns', 'specialty chocolate'),
 ('rolls/buns', 'frozen meals'),
 ('rolls/buns', 'dental care'),
 ('rolls/buns', 'root vegetables'),
 ('rolls/buns', 'detergen'),
 ('rolls/buns', 'dish cleaner'),
 ('rolls/buns', 'cling film/bags'),
 ('frankfurter', 'whole milk'),
 ('frankfurter', 'pastry'),
 ('frankfurter', 'salty snack'),
 ('frankfurter', 'sausage'),
 ('frankfurter', 'semi-finished bread'),
 ('frankfurter', 'yogurt'),
 ('frankfurter', 'soda'),
 ('frankfurter', 'pickled vegetables'),
 ('frankfurter', 'canned beer'),
 ('frankfurter', 'misc. beverages'),
 ('frankfurter', 'hygiene articles'),
 ('frankfurter', 'rolls/buns'),
 ('frankfurter', 'whipped/sour cream'),
 ('frankfurter', 'curd'),
 ('frankfurter', 'beef'),
 ('frankfurter', 'white bread'),
 ('frankfurter', 'butter'),
 ('frankfurter', 'frozen vegetables'),
 ('frankfurter', 'other vegetables'),
 ('frankfurter', 'tropical fruit'),
 ('frankfurter', 'sugar'),
 ('frankfurter', 'butter milk'),
 ('frankfurter', 'specialty chocolate'),
 ('frankfurter', 'frozen meals'),
 ('frankfurter', 'dental care'),
 ('frankfurter', 'root vegetables'),
 ('frankfurter', 'detergen'),
 ('frankfurter', 'dish cleaner'),
 ('frankfurter', 'cling film/bags'),
 ('whipped/sour cream', 'whole milk'),
 ('whipped/sour cream', 'pastry'),
 ('whipped/sour cream', 'salty snack'),
 ('whipped/sour cream', 'sausage'),
 ('whipped/sour cream', 'semi-finished bread'),
 ('whipped/sour cream', 'yogurt'),
 ('whipped/sour cream', 'soda'),
 ('whipped/sour cream', 'pickled vegetables'),
 ('whipped/sour cream', 'canned beer'),
 ('whipped/sour cream', 'misc. beverages'),
 ('whipped/sour cream', 'hygiene articles'),
 ('whipped/sour cream', 'rolls/buns'),
 ('whipped/sour cream', 'frankfurter'),
 ('whipped/sour cream', 'curd'),
 ('whipped/sour cream', 'beef'),
 ('whipped/sour cream', 'white bread'),
 ('whipped/sour cream', 'butter'),
 ('whipped/sour cream', 'frozen vegetables'),
 ('whipped/sour cream', 'other vegetables'),
 ('whipped/sour cream', 'tropical fruit'),
 ('whipped/sour cream', 'sugar'),
 ('whipped/sour cream', 'butter milk'),
 ('whipped/sour cream', 'specialty chocolate'),
 ('whipped/sour cream', 'frozen meals'),
 ('whipped/sour cream', 'dental care'),
 ('whipped/sour cream', 'root vegetables'),
 ('whipped/sour cream', 'detergen'),
 ('whipped/sour cream', 'dish cleaner'),
 ('whipped/sour cream', 'cling film/bags'),
 ('curd', 'whole milk'),
 ('curd', 'pastry'),
 ('curd', 'salty snack'),
 ('curd', 'sausage'),
 ('curd', 'semi-finished bread'),
 ('curd', 'yogurt'),
 ('curd', 'soda'),
 ('curd', 'pickled vegetables'),
 ('curd', 'canned beer'),
 ('curd', 'misc. beverages'),
 ('curd', 'hygiene articles'),
 ('curd', 'rolls/buns'),
 ('curd', 'frankfurter'),
 ('curd', 'whipped/sour cream'),
 ('curd', 'beef'),
 ('curd', 'white bread'),
 ('curd', 'butter'),
 ('curd', 'frozen vegetables'),
 ('curd', 'other vegetables'),
 ('curd', 'tropical fruit'),
 ('curd', 'sugar'),
 ('curd', 'butter milk'),
 ('curd', 'specialty chocolate'),
 ('curd', 'frozen meals'),
 ('curd', 'dental care'),
 ('curd', 'root vegetables'),
 ('curd', 'detergen'),
 ('curd', 'dish cleaner'),
 ('curd', 'cling film/bags'),
 ('beef', 'whole milk'),
 ('beef', 'pastry'),
 ('beef', 'salty snack'),
 ('beef', 'sausage'),
 ('beef', 'semi-finished bread'),
 ('beef', 'yogurt'),
 ('beef', 'soda'),
 ('beef', 'pickled vegetables'),
 ('beef', 'canned beer'),
 ('beef', 'misc. beverages'),
 ('beef', 'hygiene articles'),
 ('beef', 'rolls/buns'),
 ('beef', 'frankfurter'),
 ('beef', 'whipped/sour cream'),
 ('beef', 'curd'),
 ('beef', 'white bread'),
 ('beef', 'butter'),
 ('beef', 'frozen vegetables'),
 ('beef', 'other vegetables'),
 ('beef', 'tropical fruit'),
 ('beef', 'sugar'),
 ('beef', 'butter milk'),
 ('beef', 'specialty chocolate'),
 ('beef', 'frozen meals'),
 ('beef', 'dental care'),
 ('beef', 'root vegetables'),
 ('beef', 'detergen'),
 ('beef', 'dish cleaner'),
 ('beef', 'cling film/bags'),
 ('white bread', 'whole milk'),
 ('white bread', 'pastry'),
 ('white bread', 'salty snack'),
 ('white bread', 'sausage'),
 ('white bread', 'semi-finished bread'),
 ('white bread', 'yogurt'),
 ('white bread', 'soda'),
 ('white bread', 'pickled vegetables'),
 ('white bread', 'canned beer'),
 ('white bread', 'misc. beverages'),
 ('white bread', 'hygiene articles'),
 ('white bread', 'rolls/buns'),
 ('white bread', 'frankfurter'),
 ('white bread', 'whipped/sour cream'),
 ('white bread', 'curd'),
 ('white bread', 'beef'),
 ('white bread', 'butter'),
 ('white bread', 'frozen vegetables'),
 ('white bread', 'other vegetables'),
 ('white bread', 'tropical fruit'),
 ('white bread', 'sugar'),
 ('white bread', 'butter milk'),
 ('white bread', 'specialty chocolate'),
 ('white bread', 'frozen meals'),
 ('white bread', 'dental care'),
 ('white bread', 'root vegetables'),
 ('white bread', 'detergen'),
 ('white bread', 'dish cleaner'),
 ('white bread', 'cling film/bags'),
 ('butter', 'whole milk'),
 ('butter', 'pastry'),
 ('butter', 'salty snack'),
 ('butter', 'sausage'),
 ('butter', 'semi-finished bread'),
 ('butter', 'yogurt'),
 ('butter', 'soda'),
 ('butter', 'pickled vegetables'),
 ('butter', 'canned beer'),
 ('butter', 'misc. beverages'),
 ('butter', 'hygiene articles'),
 ('butter', 'rolls/buns'),
 ('butter', 'frankfurter'),
 ('butter', 'whipped/sour cream'),
 ('butter', 'curd'),
 ('butter', 'beef'),
 ('butter', 'white bread'),
 ('butter', 'frozen vegetables'),
 ('butter', 'other vegetables'),
 ('butter', 'tropical fruit'),
 ('butter', 'sugar'),
 ('butter', 'butter milk'),
 ('butter', 'specialty chocolate'),
 ('butter', 'frozen meals'),
 ('butter', 'dental care'),
 ('butter', 'root vegetables'),
 ('butter', 'detergen'),
 ('butter', 'dish cleaner'),
 ('butter', 'cling film/bags'),
 ('frozen vegetables', 'whole milk'),
 ('frozen vegetables', 'pastry'),
 ('frozen vegetables', 'salty snack'),
 ('frozen vegetables', 'sausage'),
 ('frozen vegetables', 'semi-finished bread'),
 ('frozen vegetables', 'yogurt'),
 ('frozen vegetables', 'soda'),
 ('frozen vegetables', 'pickled vegetables'),
 ('frozen vegetables', 'canned beer'),
 ('frozen vegetables', 'misc. beverages'),
 ('frozen vegetables', 'hygiene articles'),
 ('frozen vegetables', 'rolls/buns'),
 ('frozen vegetables', 'frankfurter'),
 ('frozen vegetables', 'whipped/sour cream'),
 ('frozen vegetables', 'curd'),
 ('frozen vegetables', 'beef'),
 ('frozen vegetables', 'white bread'),
 ('frozen vegetables', 'butter'),
 ('frozen vegetables', 'other vegetables'),
 ('frozen vegetables', 'tropical fruit'),
 ('frozen vegetables', 'sugar'),
 ('frozen vegetables', 'butter milk'),
 ('frozen vegetables', 'specialty chocolate'),
 ('frozen vegetables', 'frozen meals'),
 ('frozen vegetables', 'dental care'),
 ('frozen vegetables', 'root vegetables'),
 ('frozen vegetables', 'detergen'),
 ('frozen vegetables', 'dish cleaner'),
 ('frozen vegetables', 'cling film/bags'),
 ('other vegetables', 'whole milk'),
 ('other vegetables', 'pastry'),
 ('other vegetables', 'salty snack'),
 ('other vegetables', 'sausage'),
 ('other vegetables', 'semi-finished bread'),
 ('other vegetables', 'yogurt'),
 ('other vegetables', 'soda'),
 ('other vegetables', 'pickled vegetables'),
 ('other vegetables', 'canned beer'),
 ('other vegetables', 'misc. beverages'),
 ('other vegetables', 'hygiene articles'),
 ('other vegetables', 'rolls/buns'),
 ('other vegetables', 'frankfurter'),
 ('other vegetables', 'whipped/sour cream'),
 ('other vegetables', 'curd'),
 ('other vegetables', 'beef'),
 ('other vegetables', 'white bread'),
 ('other vegetables', 'butter'),
 ('other vegetables', 'frozen vegetables'),
 ('other vegetables', 'tropical fruit'),
 ('other vegetables', 'sugar'),
 ('other vegetables', 'butter milk'),
 ('other vegetables', 'specialty chocolate'),
 ('other vegetables', 'frozen meals'),
 ('other vegetables', 'dental care'),
 ('other vegetables', 'root vegetables'),
 ('other vegetables', 'detergen'),
 ('other vegetables', 'dish cleaner'),
 ('other vegetables', 'cling film/bags'),
 ('tropical fruit', 'whole milk'),
 ('tropical fruit', 'pastry'),
 ('tropical fruit', 'salty snack'),
 ('tropical fruit', 'sausage'),
 ('tropical fruit', 'semi-finished bread'),
 ('tropical fruit', 'yogurt'),
 ('tropical fruit', 'soda'),
 ('tropical fruit', 'pickled vegetables'),
 ('tropical fruit', 'canned beer'),
 ('tropical fruit', 'misc. beverages'),
 ('tropical fruit', 'hygiene articles'),
 ('tropical fruit', 'rolls/buns'),
 ('tropical fruit', 'frankfurter'),
 ('tropical fruit', 'whipped/sour cream'),
 ('tropical fruit', 'curd'),
 ('tropical fruit', 'beef'),
 ('tropical fruit', 'white bread'),

In [ ]:
# Filter yang ada item kombinasi yang muncul aja yang dihitung
rule_baru = []
for rule in rules:
  # Memfilter dengan nama kolom
  if len(df[(df[rule[0]]==1) & (df[rule[1]]==1)]) >0:
    rule_baru.append(rule)
rule_baru

[('whole milk', 'pastry'),
 ('whole milk', 'salty snack'),
 ('whole milk', 'sausage'),
 ('whole milk', 'semi-finished bread'),
 ('whole milk', 'yogurt'),
 ('whole milk', 'soda'),
 ('whole milk', 'rolls/buns'),
 ('whole milk', 'butter'),
 ('pastry', 'whole milk'),
 ('pastry', 'salty snack'),
 ('salty snack', 'whole milk'),
 ('salty snack', 'pastry'),
 ('sausage', 'whole milk'),
 ('sausage', 'semi-finished bread'),
 ('sausage', 'yogurt'),
 ('sausage', 'hygiene articles'),
 ('sausage', 'rolls/buns'),
 ('semi-finished bread', 'whole milk'),
 ('semi-finished bread', 'sausage'),
 ('semi-finished bread', 'yogurt'),
 ('yogurt', 'whole milk'),
 ('yogurt', 'sausage'),
 ('yogurt', 'semi-finished bread'),
 ('soda', 'whole milk'),
 ('soda', 'pickled vegetables'),
 ('soda', 'frankfurter'),
 ('soda', 'whipped/sour cream'),
 ('pickled vegetables', 'soda'),
 ('canned beer', 'misc. beverages'),
 ('misc. beverages', 'canned beer'),
 ('hygiene articles', 'sausage'),
 ('rolls/buns', 'whole milk'),
 ('rolls/buns', 'sausage'),
 ('frankfurter', 'soda'),
 ('frankfurter', 'whipped/sour cream'),
 ('frankfurter', 'curd'),
 ('whipped/sour cream', 'soda'),
 ('whipped/sour cream', 'frankfurter'),
 ('curd', 'frankfurter'),
 ('beef', 'white bread'),
 ('white bread', 'beef'),
 ('butter', 'whole milk'),
 ('frozen vegetables', 'other vegetables'),
 ('other vegetables', 'frozen vegetables'),
 ('tropical fruit', 'sugar'),
 ('sugar', 'tropical fruit'),
 ('butter milk', 'specialty chocolate'),
 ('specialty chocolate', 'butter milk'),
 ('frozen meals', 'dental care'),
 ('dental care', 'frozen meals'),
 ('root vegetables', 'detergen'),
 ('detergen', 'root vegetables'),
 ('dish cleaner', 'cling film/bags'),
 ('cling film/bags', 'dish cleaner')]

In [ ]:
hitung = {} #Ganti dictionary
for rule in rule_baru:
  banyak_data= len(df[
      (df[rule[0]]==1) & (df[rule[1]]==1)
      ])
  hitung[str(rule)] = banyak_data

hitung

{"('whole milk', 'pastry')": 1,
 "('whole milk', 'salty snack')": 1,
 "('whole milk', 'sausage')": 2,
 "('whole milk', 'semi-finished bread')": 1,
 "('whole milk', 'yogurt')": 1,
 "('whole milk', 'soda')": 1,
 "('whole milk', 'rolls/buns')": 1,
 "('whole milk', 'butter')": 1,
 "('pastry', 'whole milk')": 1,
 "('pastry', 'salty snack')": 1,
 "('salty snack', 'whole milk')": 1,
 "('salty snack', 'pastry')": 1,
 "('sausage', 'whole milk')": 2,
 "('sausage', 'semi-finished bread')": 1,
 "('sausage', 'yogurt')": 1,
 "('sausage', 'hygiene articles')": 1,
 "('sausage', 'rolls/buns')": 2,
 "('semi-finished bread', 'whole milk')": 1,
 "('semi-finished bread', 'sausage')": 1,
 "('semi-finished bread', 'yogurt')": 1,
 "('yogurt', 'whole milk')": 1,
 "('yogurt', 'sausage')": 1,
 "('yogurt', 'semi-finished bread')": 1,
 "('soda', 'whole milk')": 1,
 "('soda', 'pickled vegetables')": 1,
 "('soda', 'frankfurter')": 1,
 "('soda', 'whipped/sour cream')": 1,
 "('pickled vegetables', 'soda')": 1,
 "('canned beer', 'misc. beverages')": 1,
 "('misc. beverages', 'canned beer')": 1,
 "('hygiene articles', 'sausage')": 1,
 "('rolls/buns', 'whole milk')": 1,
 "('rolls/buns', 'sausage')": 2,
 "('frankfurter', 'soda')": 1,
 "('frankfurter', 'whipped/sour cream')": 1,
 "('frankfurter', 'curd')": 1,
 "('whipped/sour cream', 'soda')": 1,
 "('whipped/sour cream', 'frankfurter')": 1,
 "('curd', 'frankfurter')": 1,
 "('beef', 'white bread')": 1,
 "('white bread', 'beef')": 1,
 "('butter', 'whole milk')": 1,
 "('frozen vegetables', 'other vegetables')": 1,
 "('other vegetables', 'frozen vegetables')": 1,
 "('tropical fruit', 'sugar')": 1,
 "('sugar', 'tropical fruit')": 1,
 "('butter milk', 'specialty chocolate')": 1,
 "('specialty chocolate', 'butter milk')": 1,
 "('frozen meals', 'dental care')": 1,
 "('dental care', 'frozen meals')": 1,
 "('root vegetables', 'detergen')": 1,
 "('detergen', 'root vegetables')": 1,
 "('dish cleaner', 'cling film/bags')": 1,
 "('cling film/bags', 'dish cleaner')": 1}

In [ ]:
len(df)

19

In [ ]:
for item,ab in hitung.items():
  #"A->B"
  i = eval(item) #Ubah ke list dari string
  print(f"{i[0]}->{i[1]}  Confidence = {ab/df[i[0]].sum()*100}%")

whole milk->pastry  Confidence = 20.0%
whole milk->salty snack  Confidence = 20.0%
whole milk->sausage  Confidence = 40.0%
whole milk->semi-finished bread  Confidence = 20.0%
whole milk->yogurt  Confidence = 20.0%
whole milk->soda  Confidence = 20.0%
whole milk->rolls/buns  Confidence = 20.0%
whole milk->butter  Confidence = 20.0%
pastry->whole milk  Confidence = 100.0%
pastry->salty snack  Confidence = 100.0%
salty snack->whole milk  Confidence = 100.0%
salty snack->pastry  Confidence = 100.0%
sausage->whole milk  Confidence = 50.0%
sausage->semi-finished bread  Confidence = 25.0%
sausage->yogurt  Confidence = 25.0%
sausage->hygiene articles  Confidence = 25.0%
sausage->rolls/buns  Confidence = 50.0%
semi-finished bread->whole milk  Confidence = 100.0%
semi-finished bread->sausage  Confidence = 100.0%
semi-finished bread->yogurt  Confidence = 100.0%
yogurt->whole milk  Confidence = 100.0%
yogurt->sausage  Confidence = 100.0%
yogurt->semi-finished bread  Confidence = 100.0%
soda->whole milk  Confidence = 33.33333333333333%
soda->pickled vegetables  Confidence = 33.33333333333333%
soda->frankfurter  Confidence = 33.33333333333333%
soda->whipped/sour cream  Confidence = 33.33333333333333%
pickled vegetables->soda  Confidence = 100.0%
canned beer->misc. beverages  Confidence = 100.0%
misc. beverages->canned beer  Confidence = 100.0%
hygiene articles->sausage  Confidence = 100.0%
rolls/buns->whole milk  Confidence = 25.0%
rolls/buns->sausage  Confidence = 50.0%
frankfurter->soda  Confidence = 50.0%
frankfurter->whipped/sour cream  Confidence = 50.0%
frankfurter->curd  Confidence = 50.0%
whipped/sour cream->soda  Confidence = 100.0%
whipped/sour cream->frankfurter  Confidence = 100.0%
curd->frankfurter  Confidence = 100.0%
beef->white bread  Confidence = 100.0%
white bread->beef  Confidence = 100.0%
butter->whole milk  Confidence = 100.0%
frozen vegetables->other vegetables  Confidence = 100.0%
other vegetables->frozen vegetables  Confidence = 100.0%
tropical fruit->sugar  Confidence = 100.0%
sugar->tropical fruit  Confidence = 100.0%
butter milk->specialty chocolate  Confidence = 100.0%
specialty chocolate->butter milk  Confidence = 100.0%
frozen meals->dental care  Confidence = 100.0%
dental care->frozen meals  Confidence = 100.0%
root vegetables->detergen  Confidence = 100.0%
detergen->root vegetables  Confidence = 100.0%
dish cleaner->cling film/bags  Confidence = 100.0%
cling film/bags->dish cleaner  Confidence = 100.0%

#(2) KNN

Gunakan dataset ini : https://drive.google.com/file/d/1pXAJZZXCXosf0PTJkyogopKaPFxCYl22/view?usp=share_link

Kemudian buatlah tabel jarak berdasarkan data berikut ini : 

![Gambar]()
<!-- 1412 -->

In [ ]:
import pandas as pd
import math

In [ ]:
# 1. Tambahkan kolom jarak untuk menampilkan jarak dari dataset terhadap target prediksi

In [ ]:
# dataset
data = pd.read_csv('deteksi_uang_palsu.csv')

# data target prediksi
target = [172.25, 103.94, 103.68, 4.14, 3.25, 112.48]

# hitung jarak Euclidean untuk setiap data pada dataset
jarak = []
for i in range(len(data)):
    dist = 0
    for j in range(1, len(data.columns)):
        dist += (data.iloc[i,j] - target[j-1])**2
    jarak.append(math.sqrt(dist))

# tambahkan kolom jarak pada dataset
data['jarak'] = jarak

# tampilkan hasil
data

,is_genuine,diagonal,height_left,height_right,margin_low,margin_up,length,jarak
0,True,172.06,104.24,103.66,4.24,3.10,113.02,0.671267
1,True,171.66,103.68,103.41,4.35,3.33,113.74,1.458321
2,True,172.23,104.00,103.35,4.43,2.95,113.12,0.834626
3,True,172.07,104.21,103.82,4.29,3.35,113.30,0.910934
4,True,171.79,104.57,104.04,4.26,3.15,113.46,1.312593
5,False,172.00,104.23,104.52,5.76,3.37,110.94,2.421281
6,False,171.56,104.03,103.93,5.47,3.50,111.67,1.741896
7,False,171.90,104.33,104.40,4.70,3.31,112.12,1.113463
8,False,171.84,104.06,104.10,4.87,3.25,111.04,1.722034
9,False,172.11,104.14,104.15,4.84,3.28,110.98,1.738217

In [ ]:
# 2. Urutkan data berdasarkan K jarak terdekat (Untuk K nya ambil akar 2 dari banyak data)

In [ ]:
# Membaca data
df = pd.read_csv("deteksi_uang_palsu.csv")

# Menambahkan kolom jarak untuk setiap data terhadap target prediksi
target = [172.25, 103.94, 103.68, 4.14, 3.25, 112.48]
df["jarak"] = ((df.diagonal - target[0])**2 + 
               (df.height_left - target[1])**2 +
               (df.height_right - target[2])**2 +
               (df.margin_low - target[3])**2 +
               (df.margin_up - target[4])**2 +
               (df.length - target[5])**2)**0.5

# Mengurutkan data berdasarkan jarak terdekat
k = int(math.sqrt(len(df)))
sorted_df = df.sort_values(by=["jarak"]).head(k)

# Menampilkan hasil pengurutan
sorted_df

,is_genuine,diagonal,height_left,height_right,margin_low,margin_up,length,jarak
0,True,172.06,104.24,103.66,4.24,3.10,113.02,0.671267
2,True,172.23,104.00,103.35,4.43,2.95,113.12,0.834626
3,True,172.07,104.21,103.82,4.29,3.35,113.30,0.910934

In [ ]:
# 3. Tentukan apa hasil prediksinya berdasarkan label terbanyak

In [ ]:
# Target prediksi
target = [172.25, 103.94, 103.68, 4.14, 3.25, 112.48]

# Hitung jarak Euclidean
data["jarak"] = (((data["diagonal"]-target[0])**2)+((data["height_left"]-target[1])**2)+((data["height_right"]-target[2])**2)+((data["margin_low"]-target[3])**2)+((data["margin_up"]-target[4])**2)+((data["length"]-target[5])**2))**(1/2)

# Urutkan data berdasarkan jarak terdekat
k = round(len(data)**0.5)  # K = akar 2 dari banyak data
data = data.sort_values("jarak")[:k]

# Tentukan hasil prediksi berdasarkan label terbanyak
prediksi = data["is_genuine"].value_counts().idxmax()
print("Hasil prediksi:", prediksi)

Hasil prediksi: True

# (3) Analisis

> Nama : Rizky Maulana Alfauzan

> Nim : 2109116001

Penjelasan posttest : 

Pilihlah salah satu tema dari daftar tema ini :  
1. Perbankan
2. Kesehatan
3. Ritel
4. Pendidkan

Kemudian lakukan analisis dengan menggunakan struktur CRISP-DM

Dimulai dari Business Understanding Hingga Data Preparation 
<img src="https://th.bing.com/th/id/R.f8efea41ae3cd96d86fbc5b10f81ad77?rik=K4Dr%2biIaVGvW8g&riu=http%3a%2f%2fwww.dataprix.com%2ffiles%2fCRISPDM%2fMetodologia_CRISP_DM1_html_52cdbecf.png&ehk=6ONLJMCVxE421Sjt2JJPE6MfCzrL7LLhDZQPdkJTLcw%3d&risl=&pid=ImgRaw&r=0"/>

Tentukan judul dengan ketentuan setiap orang di kelas beda-beda judulnya dan sumber datasetnya (contoh bisa prediksi atau aturan asosiasi)

Catatan : Tugas ini akan berhubungan dengan posttest terakhir (pertemuan 6)

# Business Understanding

Entrepreneurial Competency adalah kemampuan yang dimiliki oleh individu untuk memulai dan menjalankan bisnis dengan sukses. Kemampuan ini meliputi berbagai aspek, seperti keterampilan manajerial, kecenderungan kewirausahaan, pemahaman pasar, inovasi, dan lain-lain.

Pentingnya kemampuan kewirausahaan dalam bisnis adalah karena kemampuan ini dapat membantu individu dalam memulai bisnis baru, mengembangkan produk baru, meningkatkan kinerja bisnis, dan mengidentifikasi peluang bisnis baru.


> **Target Bisnis :** memperoleh pemahaman yang lebih baik tentang kemampuan kewirausahaan mahasiswa dan faktor-faktor yang dapat mempengaruhi kemampuan kewirausahaan mereka untuk mengembangkan program-program pendidikan yang lebih baik dalam kewirausahaan.



> **Target Data Mining :** Dengan dataset ini dapat membantu perguruan tinggi dalam mengidentifikasi pola dan tren dalam data yang dapat membantu dalam mengembangkan program-program pendidikan yang dapat membantu mahasiswa dalam mengembangkan keterampilan kewirausahaan mereka.

# Data Understanding

In [ ]:
import pandas as pd
import seaborn as sns
import plotly.express as px
from itertools import permutations

In [ ]:
df = pd.read_csv('Entrepreneurial Competency in University Students.csv')
df

,EducationSector,IndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,MentalDisorder,KeyTraits,ReasonsForLack,y
0,Engineering Sciences,No,19,Male,Yes,No,2,2,3,3,2,2,3,Yes,Passion,NaN,1
1,Engineering Sciences,Yes,22,Male,No,Yes,3,3,3,4,4,3,4,Yes,Vision,Just not interested! (Want to work in the corp...,0
2,Engineering Sciences,No,18,Male,Yes,No,3,4,3,3,3,4,4,No,Passion,Not willing to start a venture in India and wa...,0
3,Engineering Sciences,Yes,20,Male,Yes,Yes,3,3,3,3,4,3,3,No,Resilience,Not able to take a Financial Risk,0
4,Engineering Sciences,Yes,19,Male,Yes,Yes,2,3,3,3,4,3,2,Yes,Vision,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Engineering Sciences,Yes,19,Male,Yes,Yes,4,5,4,3,4,4,5,Yes,Positivity,NaN,1
215,Engineering Sciences,Yes,19,Male,Yes,No,2,2,2,2,2,2,2,No,Work Ethic,Just not interested! (Want to work in the corp...,0
216,Engineering Sciences,Yes,22,Female,Yes,Yes,3,4,4,3,4,4,3,No,Vision,NaN,1
217,Engineering Sciences,No,19,Male,Yes,No,1,2,2,3,3,2,2,No,Passion,Lack of Knowledge,0
218,Engineering Sciences,Yes,18,Male,No,Yes,3,5,3,5,5,5,2,No,Passion,NaN,1

In [ ]:
# Melihat 5 baris pertama dari kerangka data
(df.head())

,EducationSector,IndividualProject,Age,Gender,City,Influenced,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,MentalDisorder,KeyTraits,ReasonsForLack,y
0,Engineering Sciences,No,19,Male,Yes,No,2,2,3,3,2,2,3,Yes,Passion,NaN,1
1,Engineering Sciences,Yes,22,Male,No,Yes,3,3,3,4,4,3,4,Yes,Vision,Just not interested! (Want to work in the corp...,0
2,Engineering Sciences,No,18,Male,Yes,No,3,4,3,3,3,4,4,No,Passion,Not willing to start a venture in India and wa...,0
3,Engineering Sciences,Yes,20,Male,Yes,Yes,3,3,3,3,4,3,3,No,Resilience,Not able to take a Financial Risk,0
4,Engineering Sciences,Yes,19,Male,Yes,Yes,2,3,3,3,4,3,2,Yes,Vision,NaN,1

In [ ]:
# Melihat bentuk kerangka data
(df.shape)

(219, 17)

In [ ]:
# Melihat nama kolom kerangka data
(df.columns)

Index(['EducationSector', 'IndividualProject', 'Age', 'Gender', 'City',
       'Influenced', 'Perseverance', 'DesireToTakeInitiative',
       'Competitiveness', 'SelfReliance', 'StrongNeedToAchieve',
       'SelfConfidence', 'GoodPhysicalHealth', 'MentalDisorder', 'KeyTraits',
       'ReasonsForLack', 'y'],
      dtype='object')

In [ ]:
# Melihat tipe data kolom
(df.dtypes)

EducationSector           object
IndividualProject         object
Age                        int64
Gender                    object
City                      object
Influenced                object
Perseverance               int64
DesireToTakeInitiative     int64
Competitiveness            int64
SelfReliance               int64
StrongNeedToAchieve        int64
SelfConfidence             int64
GoodPhysicalHealth         int64
MentalDisorder            object
KeyTraits                 object
ReasonsForLack            object
y                          int64
dtype: object

In [ ]:
# Melihat ringkasan statistik kerangka data
(df.describe())

,Age,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,y
count,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000
mean,19.753425,3.351598,3.621005,3.589041,3.721461,3.908676,3.575342,3.561644,0.415525
std,1.289842,0.995234,1.152467,1.110859,1.053629,1.023068,1.120098,1.100287,0.493941
min,17.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,19.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,0.000000
50%,20.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,0.000000
75%,20.000000,4.000000,5.000000,4.500000,5.000000,5.000000,4.000000,4.000000,1.000000
max,26.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1.000000

In [ ]:
# Melihat informasi umum dari dataset
(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EducationSector         219 non-null    object
 1   IndividualProject       219 non-null    object
 2   Age                     219 non-null    int64
 3   Gender                  219 non-null    object
 4   City                    219 non-null    object
 5   Influenced              219 non-null    object
 6   Perseverance            219 non-null    int64
 7   DesireToTakeInitiative  219 non-null    int64
 8   Competitiveness         219 non-null    int64
 9   SelfReliance            219 non-null    int64
 10  StrongNeedToAchieve     219 non-null    int64
 11  SelfConfidence          219 non-null    int64
 12  GoodPhysicalHealth      219 non-null    int64
 13  MentalDisorder          219 non-null    object
 14  KeyTraits               219 non-null    object
 15  ReasonsForLack          128 non-null    object
 16  y                       219 non-null    int64
dtypes: int64(9), object(8)
memory usage: 29.2+ KB

In [ ]:
# Melihat jumlah nilai unik di setiap kolom
(df.nunique())

EducationSector            9
IndividualProject          2
Age                       10
Gender                     2
City                       2
Influenced                 2
Perseverance               5
DesireToTakeInitiative     5
Competitiveness            5
SelfReliance               5
StrongNeedToAchieve        5
SelfConfidence             5
GoodPhysicalHealth         5
MentalDisorder             2
KeyTraits                  5
ReasonsForLack            44
y                          2
dtype: int64

# Data Preparation

In [ ]:
import pandas as pd
import seaborn as sns
import plotly.express as px
from itertools import permutations

In [ ]:

duplicateRows = df[df.duplicated()]
duplicateRows

# Mengecek apakah ada duplikat

Empty DataFrame
Columns: [EducationSector, IndividualProject, Age, Gender, City, Influenced, Perseverance, DesireToTakeInitiative, Competitiveness, SelfReliance, StrongNeedToAchieve, SelfConfidence, GoodPhysicalHealth, MentalDisorder, KeyTraits, ReasonsForLack, y]
Index: []

In [ ]:

df.isna().sum()

# Mengecek apakah ada missing value

EducationSector            0
IndividualProject          0
Age                        0
Gender                     0
City                       0
Influenced                 0
Perseverance               0
DesireToTakeInitiative     0
Competitiveness            0
SelfReliance               0
StrongNeedToAchieve        0
SelfConfidence             0
GoodPhysicalHealth         0
MentalDisorder             0
KeyTraits                  0
ReasonsForLack            91
y                          0
dtype: int64

In [ ]:
df_2 = pd.get_dummies(df)

# Encoding / mengubah semua tipe Categorical ke numerik

In [ ]:
df_2.head(10)

,Age,Perseverance,DesireToTakeInitiative,Competitiveness,SelfReliance,StrongNeedToAchieve,SelfConfidence,GoodPhysicalHealth,y,"EducationSector_Art, Music or Design",...,"ReasonsForLack_Lack of Knowledge, Parental Pressure","ReasonsForLack_Lack of Knowledge, Parental Pressure, Mental Block, Not able to take a Financial Risk",ReasonsForLack_Mental Block,ReasonsForLack_Not able to take a Financial Risk,"ReasonsForLack_Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation",ReasonsForLack_Not willing to start a venture in India and waiting for future relocation,ReasonsForLack_Parental Pressure,"ReasonsForLack_Parental Pressure, Not able to take a Financial Risk, Not willing to start a venture in India and waiting for future relocation",ReasonsForLack_Unwillingness to take risk,"ReasonsForLack_Unwillingness to take risk, Lack of Knowledge, Not able to take a Financial Risk"
0,19,2,2,3,3,2,2,3,1,0,...,0,0,0,0,0,0,0,0,0,0
1,22,3,3,3,4,4,3,4,0,0,...,0,0,0,0,0,0,0,0,0,0
2,18,3,4,3,3,3,4,4,0,0,...,0,0,0,0,0,1,0,0,0,0
3,20,3,3,3,3,4,3,3,0,0,...,0,0,0,1,0,0,0,0,0,0
4,19,2,3,3,3,4,3,2,1,0,...,0,0,0,0,0,0,0,0,0,0
5,19,3,3,3,3,3,3,3,1,0,...,0,0,0,0,0,0,0,0,0,0
6,19,3,2,3,3,4,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7,20,4,2,4,4,5,3,4,0,0,...,0,0,0,0,0,0,0,0,0,0
8,20,2,3,3,1,2,2,2,0,0,...,0,0,0,0,0,0,0,0,0,0
9,17,2,3,2,1,4,3,3,1,0,...,0,0,0,0,0,0,0,0,0,0